name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.32.13
      - run: pnpm install

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    # strategy:
    #   matrix: { dir: ['./packages/nextra', './packages/nextra-theme-docs'] }
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.32.13
      - run: pnpm install
      - run: npm publish
        working-directory: './packages/nextra-theme-docs'
        # working-directory: ${{ matrix.dir }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
